# Generated by Django 3.0.2 on 2020-05-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20200523_1831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordsofwisdom',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='wordsofwisdom',
            name='image',
            field=models.ImageField(default='scoan.png', upload_to='wisdom_images'),
        ),
    ]
