# Generated by Django 3.0.2 on 2020-05-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20200523_1934'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordsofwisdom',
            options={'ordering': ['date']},
        ),
    ]
