# Generated by Django 3.0.2 on 2020-05-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20200523_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField()),
                ('education', models.TextField()),
                ('skills', models.TextField()),
                ('hobby', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
