# Generated by Django 3.0.2 on 2020-05-24 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20200524_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='education',
        ),
        migrations.RemoveField(
            model_name='aboutme',
            name='experiance',
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=500)),
                ('contents', models.TextField()),
                ('myExperience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.AboutMe')),
            ],
        ),
    ]
